from enum import IntEnum


class ExitCode(IntEnum):
    SUCCESS_EXIT_CODE = 0
    GENERIC_ERROR_EXIT_CODE = 1
    MODEL_ERROR_EXIT_CODE = 2
    CHIRPEDEX_ERROR_EXIT_CODE = 3
    IMPORT_ERROR_EXIT_CODE = 4
    FILE_NOT_FOUND_ERROR_EXIT_CODE = 5
    INVALID_ARGUMENT_ERROR_EXIT_CODE = 6
