CREATE TABLE IF NOT EXISTS bird
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    common_name     TEXT NOT NULL,
    scientific_name TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS bird_sighting
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bird_id   INTEGER NOT NULL REFERENCES bird(id),
    timestamp TIMESTAMP,
    location  TEXT
);
