name: Run Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v6
        with:
          fetch-tags: 'true'

      - name: Build docker image
        run: docker compose build chirpedex-test

      - name: Run tests in Docker
        run: docker compose run --rm chirpedex-test
